# Generated by Django 5.0.6 on 2024-05-30 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_m', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_p', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=60)),
                ('valor', models.IntegerField()),
                ('foto', models.ImageField(upload_to='img')),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion_producto', models.TextField(default='Descripcion')),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='FerremasApp.categoria')),
                ('marca', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='FerremasApp.marca')),
            ],
        ),
    ]
